spring:
   profiles:
     active: dev
   application:
     name: dynamic form
   main:
     allow-bean-definition-overriding: true
   data:
     mongodb:
       uri: mongodb+srv://ramkishor0509:Ram_9450@cluster0.7aluoj1.mongodb.net/demo?ssl=true&authSource=admin&readWriteAnyDatabase=true&w=majority
       database: demo
server: 
  port: 8081
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: true
